"""initial schema

Revision ID: 0281f8a08728
Revises: 39e4dfb61037
Create Date: 2025-11-23 12:38:43.388950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0281f8a08728'
down_revision = '39e4dfb61037'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('certifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('attestation_id', sa.String(), nullable=False),
    sa.Column('issued_by', sa.String(length=255), nullable=True),
    sa.Column('issued_date', sa.DateTime(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attestation_id'], ['attestations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('attestations', 'organization_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('attestations', 'standard_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_attestations_id'), table_name='attestations')
    op.drop_column('attestations', 'updated_at')
    op.add_column('audit_logs', sa.Column('details', sa.Text(), nullable=True))
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'changes')
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'resource')
    op.drop_column('audit_logs', 'ip_address')
    op.add_column('evidence', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('evidence', sa.Column('url', sa.String(length=1024), nullable=True))
    op.add_column('evidence', sa.Column('metadata_json', sa.Text(), nullable=True))
    op.add_column('evidence', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('evidence', 'attestation_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('evidence_hash_key'), 'evidence', type_='unique')
    op.drop_column('evidence', 'filename')
    op.drop_column('evidence', 'size')
    op.drop_column('evidence', 'hash')
    op.drop_column('evidence', 'encrypted')
    op.drop_column('evidence', 'mime_type')
    op.drop_column('evidence', 's3_path')
    op.drop_column('evidence', 'uploaded_at')
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('standards', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('standards', 'version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('standards', 'created_at')
    op.drop_column('standards', 'pillars')
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('role_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.drop_constraint(op.f('users_organization_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'name')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('ADMIN', 'ENTERPRISE', 'AUDITOR', 'REGULATOR', name='userrole'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_organization_id_fkey'), 'users', 'organizations', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'full_name')
    op.add_column('standards', sa.Column('pillars', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('standards', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('standards', 'version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('standards', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('evidence', sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('evidence', sa.Column('s3_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('evidence', sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('evidence', sa.Column('encrypted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('evidence', sa.Column('hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('evidence', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('evidence', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('evidence_hash_key'), 'evidence', ['hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('evidence', 'attestation_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('evidence', 'created_at')
    op.drop_column('evidence', 'metadata_json')
    op.drop_column('evidence', 'url')
    op.drop_column('evidence', 'name')
    op.add_column('audit_logs', sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('resource', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('resource_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('changes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('audit_logs', 'details')
    op.add_column('attestations', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_attestations_id'), 'attestations', ['id'], unique=False)
    op.alter_column('attestations', 'standard_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('attestations', 'organization_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('certifications')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
